# Generated by Django 4.2 on 2023-04-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_bandmember_band_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='listen_on_spotify',
            field=models.URLField(verbose_name='Listen to'),
        ),
    ]
