# Generated by Django 4.2 on 2023-04-26 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_alter_band_listen_on_spotify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='albums_out',
        ),
        migrations.AddField(
            model_name='album',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bands.band'),
        ),
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.IntegerField(blank=True),
        ),
    ]
