# Generated by Django 4.2 on 2023-04-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_remove_band_albums_out_album_band_alter_album_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='band',
        ),
        migrations.AddField(
            model_name='band',
            name='albums_out',
            field=models.ManyToManyField(blank=True, to='bands.album'),
        ),
    ]
