# Generated by Django 4.2 on 2023-04-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0008_remove_myuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
    ]
