# Generated by Django 4.2 on 2023-04-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0009_myuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='sug_password',
            field=models.CharField(default='Mkl12mmNd-3', max_length=200),
        ),
    ]
