# Generated by Django 4.2 on 2023-04-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0010_myuser_sug_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='sug_password',
            new_name='suggested_password',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(default='examp@le.com', max_length=254),
        ),
    ]
