# Generated by Django 4.2 on 2023-04-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0011_rename_sug_password_myuser_suggested_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='in_lists',
        ),
    ]
