# Generated by Django 4.2 on 2023-04-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0012_remove_band_in_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='band_image',
            field=models.ImageField(default='image', upload_to='images/'),
        ),
    ]
