# Generated by Django 4.2 on 2023-04-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0013_band_band_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(default='image', upload_to='images/'),
        ),
    ]
