# Generated by Django 4.2 on 2023-04-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0014_album_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='creator',
            field=models.IntegerField(default=1),
        ),
    ]
